models/Event.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "events".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $published_at
 * @property string $created_at
 * @property string $updated_at
 */
class Event extends ActiveRecord
{
    public $present = true;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'events';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'published_at'], 'required'],
            [['published_at', 'present', 'comment'], 'safe'],
            [['title'], 'string', 'max' => 255]
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'value' => function() {
                    return date('Y-m-d H:i:s');
                }
            ],
        ];
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMembers()
    {
        return $this->hasMany(Member::className(), ['event_id' => 'id'])->with('user')->indexBy('user_id');
    }
    
    public function getMemberCount()
    {
        return Member::find(['event_id' => $this->id])->count();
    }
    
    /**
     * @param User $user
     * @return boolean
     */
    public function isMember($user)
    {
        return $this->getMember($user) !== null;
    }
    
    /**
     * @param User $user
     * @param string $status
     * @return boolean
     */
    public function isMemberStatus($user, $status)
    {
        $m = $this->getMember($user);
        return $m !== null && $m->status === $status;
    }
    
    
    
    /**
     * @staticvar array $cache
     * @param type $user
     * @return Member
     */
    public function getMember($user)
    {
        static $cache = [];
        $key = $this->id . '-' . $user->id;
        if (!isset($cache[$key])) {
            $cache[$key] = Member::findOne(['event_id' => $this->id, 'user_id' => $user->id]);
        }
        return $cache[$key];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'title' => 'Название',
            'comment' => 'Комментарий',
            'published_at' => 'Дата',
            'present' => 'Буду!',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function isExpired()
    {
        return date('Y-m-d') > $this->published_at;
    }
    
    public function apply($user, $member = null)
    {
        if ($member === null) {
            $member = new Member(['scenario' => Member::STATUS_APPLY]);
        }
        $member->user_id = $user->id;
        $member->event_id = $this->id;
        $member->status = Member::STATUS_APPLY;
        return $member->save();
    }
    
    public function deny($user, $member)
    {
        $member->user_id = $user->id;
        $member->event_id = $this->id;
        $member->status = Member::STATUS_DENY;
        return $member->save();
    }
    
    
    public function beforeSave($insert)
    {
        $this->published_at = date('Y-m-d', strtotime($this->published_at));
        return parent::beforeSave($insert);
    }
    
    public function afterDelete()
    {
        parent::afterDelete();
        Member::deleteAll(['event_id' => $this->id]);
    }
    
}

controllers/EventsController.php
<?php

namespace app\controllers;

use app\models\Event,
    app\models\Member,
    app\models\User,
    Yii,
    yii\data\ActiveDataProvider,
    yii\filters\AccessControl,
    yii\filters\VerbFilter,
    yii\helpers\Json,
    yii\web\Controller,
    yii\web\ForbiddenHttpException,
    yii\web\NotFoundHttpException;

/**
 * EventsController implements the CRUD actions for Event model.
 */
class EventsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete', 'deny'],
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'delete', 'deny'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Event::find()->with('user')->orderBy('published_at DESC');
        
        $user = null;
        if ($userId = Yii::$app->request->get('userId', false) && $user = User::findOne($userId)) {
            $query->andWhere('user_id = :userId', [':userId' => $user->id]);
        }
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id), 
            'users' => User::find()->withStatus(User::STATUS_ACTIVE)->asArray()->all()
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event;
        $model->user_id = Yii::$app->user->getId();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model->present) {
                $model->apply(Yii::$app->getUser()->getIdentity());
            }
            $this->sendEmails($model);
            Yii::$app->getSession()->setFlash('success', 'Событие было успешно создано.');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if (Yii::$app->getUser()->getId() != $model->user_id) {
            throw new ForbiddenHttpException('Hello Radja');
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->getUser()->getId() != $model->user_id) {
            throw new ForbiddenHttpException('Hello Radja');
        }
        $model->delete();

        return $this->redirect(['index']);
    }
    
    public function actionDeny($id)
    {
        $event = $this->findModel($id);
        $user = Yii::$app->getUser()->getIdentity();
        $model = $event->getMember($user);
        $model = $model ? : new Member;
        $model->setScenario(Member::STATUS_DENY);
        
        if ($model->load(Yii::$app->request->post()) && $event->deny($user, $model)) {
            return Json::encode([
                'success' => true,
                'html' => $this->renderPartial('_view', ['model' => $event]),
                'id' => $event->id
            ]);
        } else {
            return $this->renderAjax('member/deny', ['model' => $model]);
        }
    }
    
    public function actionApply($id, $force = 1)
    {
        $event = $this->findModel($id);
        $user = Yii::$app->getUser()->getIdentity();
        $model = $event->getMember($user);
        $model = $model ? : new Member;
        $model->setScenario(Member::STATUS_APPLY);
        
        if (($force || $model->load(Yii::$app->request->post())) && $event->apply($user, $model)) {
            return Json::encode([
                'success' => true,
                'html' => $force ? 
                    $this->renderPartial('_view', ['model' => $event]) : 
                    $this->renderPartial('member/_view', ['member' => $model, 'model' => $event, 'user' => $user->toArray()]),
                'id' => $force ? $event->id : $model->user_id
            ]);
        } else {
            return $this->renderAjax('member/apply', ['model' => $model]);
        }
    }
    
    /**
     * @param \app\models\Event $event
     */
    public function sendEmails($event)
    {
        $users = User::find(['status' => User::STATUS_ACTIVE])->indexBy('id')->asArray()->all();
        unset($users[$event->user_id]);
        if (empty($users)) {
            return;
        }
        
        $mailer = Yii::$app->mail;
        foreach ($users as $user) {
            $mailer->compose('new-event', ['user' => $user, 'event' => $event])
                ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name . ' robot'])
                ->setTo($user['email'])
                ->setSubject('Новое событие: ' . \yii\helpers\Html::encode($event->title))
                ->send();
        }
        return true;
    }
    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/events/_form.php
<?php

use kartik\widgets\DatePicker,
    yii\helpers\Html,
    kartik\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Event $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="event-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model, 'published_at')->widget(DatePicker::className(), [
        'pluginOptions' => [
            'autoclose' => true,
            'format' => 'dd-M-yyyy',
            'startDate' => date('U')
        ]
    ]) ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 5]) ?>
    <?= $form->field($model, 'present')->checkbox() ?>
    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Редактировать', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/events/_view.php
<?php

use app\models\Member,
    yii\helpers\Html,
    yii\helpers\Url;

$app = Yii::$app;
$expired = $model->isExpired();
$user = $app->getUser();

?>
<tr class="event <?= $expired ? 'expired' : ''?>" id="event-<?= $model->id ?>">
    <td class="title">
        <h2><?= Html::a(Html::encode($model->title), ['/events/view', 'id' => $model->id], ['title' => Html::encode($model->title)]) ?></h2>
    </td>
    <td class="date"><?= $app->getFormatter()->asDate($model->published_at, 'full') ?></td>    
    <td class="control">
        <?php if (!$expired && !$user->getIsGuest()) : ?>
            <?php 
                $apply = $model->isMemberStatus($user->getIdentity(), Member::STATUS_APPLY);
                $deny = $model->isMemberStatus($user->getIdentity(), Member::STATUS_DENY);
            ?>
            
            <?= Html::a('', $apply ? '#' : ['/events/apply', 'id' => $model->id], [
                'class' => 'apply' . ($apply ? ' disabled' : ''),
                'title' => 'Буду!'
            ]) ?>
            &nbsp;&nbsp;
            <?= Html::a('', $deny ? '#' : ['/events/deny', 'id' => $model->id], [
                'class' => 'deny' . ($deny ? ' disabled' : ''),
                'title' => 'Есть дела поважнее'
            ]) ?>
        <?php endif ?>
    </td>    
</tr>

views/events/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Event $model
 */

$this->title = 'Создание';
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 */
$this->title = 'Все события';
$this->params['breadcrumbs'][] = 'События';
if ($eventId = Yii::$app->request->get('eventId', false)) {
    $this->registerJs('EVENT_ID = ' . (int) $eventId. ';', $this::POS_BEGIN);
}
?>
<div class="event-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать событие', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['tag' => false],
        'itemView' => '_view',
        'layout' => "{summary}\n<div id=\"events\"><table class=\"table\"><tbody>{items}</tbody></table></div>\n{pager}"
    ]) ?>

</div>

views/events/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Event $model
 */

$this->title = 'Update Event: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/view.php
<?php

use yii\helpers\Html,
    yii\widgets\DetailView;

/**
 * @var yii\web\View $this 
 * @var app\models\Event $model
 */
$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$members = $model->members;
?>
<div class="event-view">
    <div class="pull-right">
    <?php if (Yii::$app->getUser()->getId() == $model->user_id) : ?>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Согласны удалить это событие?',
                'method' => 'post',
            ],
        ]) ?>
    <?php else : ?>
        <strong><?= Html::encode($model->user->username)?></strong>
    <?php endif; ?>
    </div>
    <h1><?= Html::encode($this->title) ?> <small><?= Yii::$app->getFormatter()->asDate($model->published_at) ?></small></h1>
    
    <p><?= nl2br(Html::encode($model->comment))?></p>
    
    <?php 
        $stat = ['apply' => 0, 'deny' => 0];
    ?>
    <table class="table" id="members">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Комментарий</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $i => $user) : ?>
                <?php 
                    $member = null;
                    if (isset($members[$user['id']])) {
                        $member = $members[$user['id']];
                        $stat[$member->status]++;
                    }
                ?>
                <?= $this->render('member/_view', [
                    'member' => $member, 
                    'model' => $model, 
                    'user' => $user
                ]) ?>
            <?php endforeach; ?> 
        </tbody>
    </table>
    <div class="well pull-right" style="width: 200px;">
        За: <?= $stat['apply'] ?>, против: <?= $stat['deny'] ?>, всего: <?= count($users) ?>
    </div>
</div>